#!/bin/bash
# mac-gh-bridge.sh — macOS 自动化管线 → GitHub 桥接器
# @capability: github-integration
# @capability: pipeline-bridge
#
# 四条接入路径:
#   bash mac-gh-bridge.sh probe-watchdog  死探针监控 → Issue
#   bash mac-gh-bridge.sh daily-digest    每日汇总 → Issue
#   bash mac-gh-bridge.sh evolve-deploy   部署变更 → PR
#   bash mac-gh-bridge.sh doctor-alert    健康异常 → Issue
#
# 前置: GH_TOKEN 环境变量或 gh 已认证

set -e

REPO="${GH_REPO:-hAcKlyc/mino}"
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
BRIDGE_STATE="$HOME/.mac-gh-bridge-state.json"

[ -z "$GH_TOKEN" ] && { echo "❌ GH_TOKEN 未设置"; exit 1; }
export HTTPS_PROXY="${HTTPS_PROXY:-http://127.0.0.1:7890}"

# ═══ 状态管理 ═══
state_get() { python3 -c "import json; f=open('$BRIDGE_STATE'); d=json.load(f); print(d.get('$1',''))" 2>/dev/null || echo ""; }
state_set() {
  python3 -c "
import json, os
d = {}
if os.path.exists('$BRIDGE_STATE'):
    with open('$BRIDGE_STATE') as f: d = json.load(f)
d['$1'] = '$2'
with open('$BRIDGE_STATE','w') as f: json.dump(d,f,indent=2)
" 2>/dev/null
}

# ═══ 路径1: 死探针监控 ═══
probe_watchdog() {
  echo "═══ Probe 看门狗 ═══"

  # 当前死探针快照
  local current=$(bash "$SCRIPTS_DIR/mac-probe.sh" all 2>/dev/null | grep "🔴" | sed 's/.*🔴 //' | awk '{print $1}' | sort | tr '\n' '|')

  # 上次基线
  local baseline=$(state_get "dead_probes")

  if [ "$current" = "$baseline" ]; then
    echo "  ✅ 无新死探针——基线一致"
    return 0
  fi

  # 计算差异
  local new_dead=$(python3 -c "
b=set('''$baseline'''.split('|') if '''$baseline''' else [])
c=set('''$current'''.split('|'))
new = c - b
fixed = b - c
if new: print('NEW:' + ','.join(sorted(new)))
if fixed: print('FIXED:' + ','.join(sorted(fixed)))
" 2>/dev/null)

  local has_new=$(echo "$new_dead" | grep -c "NEW:" 2>/dev/null | xargs || echo 0)

  if [ "$has_new" -gt 0 ]; then
    local new_list=$(echo "$new_dead" | grep "NEW:" | cut -d: -f2)
    local body="## 🔴 新死探针检测

**时间**: $(date '+%Y-%m-%d %H:%M')
**macOS**: $(sw_vers -productVersion 2>/dev/null)

### 新增死路
$(echo "$new_list" | tr ',' '\n' | while read p; do echo "- \`$p\`"; done)

### 当前全量死探针
$(echo "$current" | tr '|' '\n' | while read p; do [ -n "$p" ] && echo "- $p"; done)

---
🤖 Generated by mac-gh-bridge.sh"

    gh issue create --repo "$REPO" \
      --title "🔴 死探针告警: $new_list" \
      --body "$body" \
      --label "automation,bug" 2>&1

    state_set "dead_probes" "$current"
    echo "  🚨 Issue 已创建——新死探针: $new_list"
  fi

  # 如果有修复的，也更新基线
  state_set "dead_probes" "$current"
  local has_fixed=$(echo "$new_dead" | grep -c "FIXED:" 2>/dev/null || echo 0)
  [ "$has_fixed" -gt 0 ] && echo "  ✅ 有探针恢复: $(echo "$new_dead" | grep FIXED: | cut -d: -f2)"
}

# ═══ 路径2: 每日汇总 ═══
daily_digest() {
  echo "═══ 每日汇总 ═══"

  local today=$(date +%Y-%m-%d)
  local last_digest=$(state_get "last_digest_date")

  [ "$today" = "$last_digest" ] && { echo "  ✅ 今日已汇总——跳过"; return 0; }

  # 收集各路报告
  local learn_summary=$(bash "$SCRIPTS_DIR/mac-learn-report.sh" 2>/dev/null | head -10)
  local evolve_status=$(bash "$SCRIPTS_DIR/mac-evolve.sh" --status 2>/dev/null | head -15)
  local activity_health=$(bash "$SCRIPTS_DIR/mac-activity.sh" --health 2>/dev/null | head -10)
  local doctor_score=$(bash "$SCRIPTS_DIR/mac-doctor.sh" 2>/dev/null | grep "评分\|问题\|RATING" | tr '\n' ' ')

  local body="## 📊 每日自动化汇总 — $today

### 🧠 学习引擎
\`\`\`
$learn_summary
\`\`\`

### 🧬 进化状态
\`\`\`
$evolve_status
\`\`\`

### 🩺 健康评分
$doctor_score

### 🩺 活动健康
\`\`\`
$activity_health
\`\`\`

---
🤖 Generated by mac-gh-bridge.sh · $(date '+%H:%M')"

  gh issue create --repo "$REPO" \
    --title "📊 每日自动化汇总 — $today" \
    --body "$body" \
    --label "automation,daily-digest" 2>&1

  state_set "last_digest_date" "$today"
  echo "  ✅ 每日汇总已创建"
}

# ═══ 路径3: 进化部署 → PR ═══
evolve_deploy() {
  echo "═══ 进化部署追踪 ═══"

  # 检查是否有未提交的配置变更
  local changes=""
  for f in ~/.skhdrc ~/.mac-rules.yml ~/Library/LaunchAgents/com.user.*.plist; do
    [ -f "$f" ] && git -C "$HOME" diff --no-index /dev/null "$f" 2>/dev/null | head -5 && changes="$changes $f"
  done

  if [ -z "$changes" ]; then
    echo "  ✅ 无配置变更——跳过 PR"
    return 0
  fi

  # 创建分支 + 提交 + PR
  local branch="evolve/$(date +%Y%m%d-%H%M%S)"
  local title="🧬 自进化引擎部署 — $(date '+%Y-%m-%d %H:%M')"

  git -C "$HOME" checkout -b "$branch" 2>/dev/null || true
  for f in $changes; do git -C "$HOME" add "$f" 2>/dev/null; done
  git -C "$HOME" commit -m "$title" 2>/dev/null || { echo "  ⚠️ 无变更可提交"; return 0; }

  gh pr create --repo "$REPO" \
    --title "$title" \
    --body "自动部署的配置变更:
$(for f in $changes; do echo "- \`$f\`"; done)

🤖 Generated by mac-gh-bridge.sh" 2>&1

  echo "  ✅ PR 已创建"
}

# ═══ 路径4: 健康异常告警 ═══
doctor_alert() {
  echo "═══ 健康异常监控 ═══"

  local score=$(bash "$SCRIPTS_DIR/mac-doctor.sh" 2>/dev/null | grep -o '评分: [0-9]*/' | grep -o '[0-9]*' | head -1)
  local last_score=$(state_get "last_doctor_score")

  [ -z "$score" ] && { echo "  ⚠️ 无法获取评分"; return 1; }

  if [ -n "$last_score" ] && [ "$score" -lt "$last_score" ] && [ "$score" -lt 70 ]; then
    local body="## 🚨 健康评分下降

| 指标 | 上次 | 本次 |
|------|------|------|
| 评分 | $last_score/100 | $score/100 |
| 变化 | — | **-$((last_score - score))** |

### 当前问题
$(bash "$SCRIPTS_DIR/mac-doctor.sh" 2>/dev/null | grep "❌" | head -10)

---
🤖 Generated by mac-gh-bridge.sh · $(date '+%H:%M')"

    gh issue create --repo "$REPO" \
      --title "🚨 健康评分下降: $last_score → $score" \
      --body "$body" \
      --label "automation,health-alert" 2>&1

    echo "  🚨 健康告警 Issue 已创建"
  else
    echo "  ✅ 评分正常 ($score/100)"
  fi

  state_set "last_doctor_score" "$score"
}

# ═══ 主入口 ═══
case "${1:-}" in
  probe-watchdog)   probe_watchdog ;;
  daily-digest)     daily_digest ;;
  evolve-deploy)    evolve_deploy ;;
  doctor-alert)     doctor_alert ;;
  all)
    probe_watchdog
    echo ""; daily_digest
    echo ""; evolve_deploy
    echo ""; doctor_alert
    ;;
  *)
    echo "用法: bash mac-gh-bridge.sh <path>"
    echo ""
    echo "路径:"
    echo "  probe-watchdog   死探针监控 → Issue"
    echo "  daily-digest     每日汇总 → Issue"
    echo "  evolve-deploy    部署变更 → PR"
    echo "  doctor-alert     健康异常 → Issue"
    echo "  all              全部四条路径"
    exit 1
    ;;
esac
