$ntuser = Join-Path $env:USERPROFILE 'NTUSER.DAT'
if (Test-Path $ntuser) {
    $sizeMB = [math]::Round((Get-Item $ntuser).Length/1MB, 2)
    Write-Host "NTUSER.DAT: $sizeMB MB"
}
Write-Host ""
Write-Host "=== Registry Cleanup Candidates ==="
Write-Host ""
Write-Host "1. Orphaned App Paths (2 entries):"
Write-Host "   - WORDPAD.EXE -> C:\Program Files\Windows NT\Accessories\WORDPAD.EXE"
Write-Host "   - WRITE.EXE -> C:\Program Files\Windows NT\Accessories\WORDPAD.EXE"
Write-Host ""
Write-Host "2. Orphaned Uninstall Entries (2 real):"
Write-Host "   - WeChat (C:\Program Files\Tencent\Weixin) - directory missing"
Write-Host "   - Clash Verge (C:\Program Files\Clash Verge) - directory missing"
Write-Host ""
Write-Host "3. Firewall Rule (1 entry):"
Write-Host "   - FanQieHuYan (C:\Program Files (x86)\FanQieHuYan\FanQieHuYan.exe) - already uninstalled"
Write-Host ""
Write-Host "4. Software Registry Residue:"
Write-Host "   - HKCU:\Software\CareUEyes - already uninstalled"
Write-Host ""
Write-Host "5. Clean items (no action needed):"
Write-Host "   - Startup entries: all valid"
Write-Host "   - Shell extensions: all valid"
Write-Host "   - COM registrations (sampled): all valid"
Write-Host "   - Context menu handlers: all valid"
Write-Host "   - WER entries: minimal (5)"
Write-Host "   - MRU entries: minimal"
