# ============================================================
#  workplace.ps1 - Workplace automation module
#  Mirror of macOS workplace automation pipelines
#
#  Commands: brief | email | weekly | organize | push | research
# ============================================================

function Invoke-WorkplaceCommand {
    param(
        [Parameter(Mandatory)]
        [ValidateSet('brief','email','weekly','organize','push','research')]
        [string]$Command,
        [string]$Extra
    )
    switch ($Command) {
        'brief'    { Invoke-WorkplaceBrief @(if ($Extra) { $Extra -split '\s+' } else { @() }) }
        'email'    { Invoke-WorkplaceEmail }
        'weekly'   { Invoke-WorkplaceWeekly }
        'organize' { Invoke-WorkplaceOrganize }
        'push'     { Invoke-WorkplacePush -Target $Extra }
        'research' { Invoke-WorkplaceResearch -Query $Extra }
    }
}

# --- brief: Morning financial briefing ---
function Invoke-WorkplaceBrief {
    param([string[]]$Args)
    Write-Banner 'Morning Brief Generator'

    $date = Get-Date -Format 'yyyy-MM-dd'
    $outputDir = Join-Path $script:HubRoot '..\briefs'
    if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force | Out-Null }

    $outputFile = Join-Path $outputDir "brief-$date.md"

    Write-Host '  Morning Brief Template' -ForegroundColor Yellow
    Write-Host '  ========================' -ForegroundColor Yellow
    Write-Host ''
    Write-Host "  Date: $date" -ForegroundColor White
    Write-Host ''

    $sections = @(
        @{Title='1. Major Financial Cases / Risk Events'; Icon='[!!]'},
        @{Title='2. Interest Rate Changes (PBOC, LPR)'; Icon='[$$]'},
        @{Title='3. Financial Innovation (Tech/Green/Inclusive)'; Icon='[++]'},
        @{Title='4. New Policies / Regulations'; Icon='[..]'}
    )

    foreach ($s in $sections) {
        Write-Host "  $($s.Icon) $($s.Title)" -ForegroundColor Cyan
        Write-Host ('  ' + '-' * 40) -ForegroundColor Gray
        Write-Host ''
    }

    Write-Host "  ---" -ForegroundColor Gray
    Write-Host "  This module generates the structure. AI fills the content." -ForegroundColor Gray
    Write-Host "  For auto-generation, set up a myagents cron task:" -ForegroundColor Gray
    Write-Host "    myagents cron add --name Mino-Morning-Brief --prompt-file brief-prompt.txt --schedule '30 6 * * 1-5'" -ForegroundColor DarkGray
    Write-Host ''

    # Write template to file
    $template = @"
# Morning Financial Brief - $date

> Auto-generated by mino workplace brief

## 1. Major Financial Cases / Risk Events



## 2. Interest Rate Changes



## 3. Financial Innovation



## 4. New Policies / Regulations



---
*Generated at $(Get-Date -Format 'HH:mm') | mino.ps1*
"@
    if (-not $script:DryRun) {
        $template | Out-File -FilePath $outputFile -Encoding UTF8
        Write-Mino "Template saved: $outputFile" -Level SUCCESS
    }
}

# --- email: Triage ---
function Invoke-WorkplaceEmail {
    Write-Banner 'Email Triage'
    Write-Host '  Email triage requires Outlook COM (not installed on this machine).' -ForegroundColor Yellow
    Write-Host '  For web-based email, use the research command with URL:' -ForegroundColor Gray
    Write-Host '    mino workplace research "check my gmail"' -ForegroundColor Gray
    Write-Host ''
}

# --- weekly: Git report ---
function Invoke-WorkplaceWeekly {
    Write-Banner 'Weekly Report Generator'

    $repos = @(
        "$env:USERPROFILE\.myagents\projects\mino"
        "$env:USERPROFILE\.myagents"
    )

    $since = (Get-Date).AddDays(-7).ToString('yyyy-MM-dd')
    $weekStart = (Get-Date).AddDays(-(Get-Date).DayOfWeek.value__).ToString('MM-dd')
    $weekEnd = (Get-Date).ToString('MM-dd')

    Write-Host "  Week: $weekStart -> $weekEnd" -ForegroundColor White
    Write-Host ''

    foreach ($repoPath in $repos) {
        if (-not (Test-Path (Join-Path $repoPath '.git'))) {
            Write-Host "  Skip (not a repo): $repoPath" -ForegroundColor Gray
            continue
        }

        Push-Location $repoPath
        try {
            $repoName = Split-Path $repoPath -Leaf
            $count = (git log --since=$since --oneline 2>$null | Measure-Object).Count
            Write-Host "  --- $repoName ($count commits) ---" -ForegroundColor Yellow

            if ($count -gt 0) {
                git log --since=$since --oneline --no-merges 2>$null | ForEach-Object {
                    Write-Host "    $_" -ForegroundColor Gray
                }
            }
            Write-Host ''
        }
        finally { Pop-Location }
    }

    Write-Mino 'Weekly report generated' -Level SUCCESS
}

# --- organize: File organization ---
function Invoke-WorkplaceOrganize {
    Write-Banner 'File Organizer'

    $downloads = "$env:USERPROFILE\Downloads"
    $desktop   = "$env:USERPROFILE\Desktop"

    # Stats
    foreach ($dir in @($downloads, $desktop)) {
        if (-not (Test-Path $dir)) { continue }
        $label = Split-Path $dir -Leaf
        $files = Get-ChildItem $dir -File -ErrorAction SilentlyContinue
        $dirs  = Get-ChildItem $dir -Directory -ErrorAction SilentlyContinue

        Write-Host "  --- $label ---" -ForegroundColor Yellow
        Write-Host "  Files: $($files.Count) | Folders: $($dirs.Count) | Total: $([math]::Round(($files | Measure-Object Length -Sum).Sum / 1MB, 1))MB" -ForegroundColor Gray

        # File type breakdown
        $files | Group-Object Extension | Sort-Object Count -Descending | Select-Object -First 5 |
            ForEach-Object { Write-Host "    $($_.Name.PadRight(10)) x $($_.Count)" -ForegroundColor Gray }

        # Old files (>30 days) that could be archived
        $oldFiles = $files | Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-30) }
        if ($oldFiles.Count -gt 0) {
            Write-Host "    [!] $($oldFiles.Count) files older than 30 days" -ForegroundColor Yellow
        }
        Write-Host ''
    }

    Write-Host '  Run with --dry-run to preview only.' -ForegroundColor Gray
    Write-Host '  To auto-organize: mino workplace organize --execute (coming soon)' -ForegroundColor Gray
    Write-Host ''
}

# --- push: WeChat push ---
function Invoke-WorkplacePush {
    param([string]$Target)
    Write-Banner 'WeChat Push'
    Write-Host '  WeChat push via myagents session send:' -ForegroundColor Yellow
    Write-Host ''
    Write-Host '  # Find active Mino bot session' -ForegroundColor Gray
    Write-Host '  python3 ~/.myagents/heartbeats/register_session.py lookup mino' -ForegroundColor DarkGray
    Write-Host ''
    Write-Host '  # Send message' -ForegroundColor Gray
    Write-Host '  myagents session send <sessionId> --prompt-file /path/to/message.txt' -ForegroundColor DarkGray
    Write-Host ''

    if ($Target) {
        Write-Mino "Push target: $Target (use session send for delivery)" -Level INFO
    }
}

# --- research: Quick research ---
function Invoke-WorkplaceResearch {
    param([string]$Query)
    Write-Banner 'Quick Research'

    if (-not $Query) {
        Write-Host '  Usage: mino workplace research "<query>"' -ForegroundColor Yellow
        Write-Host '  Example: mino workplace research "latest PBOC LPR rate change"' -ForegroundColor Gray
        Write-Host ''
        return
    }

    Write-Host "  Query: $Query" -ForegroundColor White
    Write-Host ''

    # Check gh CLI
    $gh = Get-Command gh -ErrorAction SilentlyContinue

    # Gather system context first
    Write-Host '  --- System Context ---' -ForegroundColor Yellow
    $snap = Get-SystemSnapshot
    Write-Host "  Date: $($snap.Timestamp)" -ForegroundColor Gray
    Write-Host "  Machine: $($snap.ComputerName)" -ForegroundColor Gray
    Write-Host ''

    # Search suggestions
    Write-Host '  --- Search Channels ---' -ForegroundColor Yellow
    Write-Host '  1. Web Search (use Claude WebSearch tool)' -ForegroundColor Gray
    Write-Host '  2. GitHub Search (if code-related)' -ForegroundColor Gray
    if ($gh) {
        Write-Host '  3. gh CLI issue/PR search' -ForegroundColor Gray
    }
    Write-Host ''

    Write-Host '  --- Recommended Deep-Research Pipeline ---' -ForegroundColor Yellow
    Write-Host "  /deep-research `"$Query`"" -ForegroundColor Cyan
    Write-Host ''

    Write-Mino "Research scaffolding ready for: $Query" -Level SUCCESS
}
